version: '3.7'
services:
  miner:
    container_name: miner
    restart: unless-stopped
    image: sybil-miner:nightly
    ports:
        - "3001:3001"
    # You may also create a .env file in the same folder as the docker-compose.yml file
    environment:
        LOG_LEVEL: info

  validator:
    container_name: validator
    image: sybil-validator:nightly
    env_file:
        - .env
    restart: unless-stopped
    ports:
        - "3000:3000"
    # You may also create a .env file in the same folder as the docker-compose.yml file
    environment:
        LOG_LEVEL: info
        MAXMIND_LICENSE_KEY:
        # PUBLIC_URL: "http://localhost:3000"
        IP2LOCATION_DOWNLOAD_TOKEN: 
    depends_on:
        - postgres
    volumes:
        # - ./node_modules/geoip-lite/data:/app/node_modules/geoip-lite/data
        - maxmind_data:/app/node_modules/geoip-lite/data
        # - ./IP2LOCATION-LITE-ASN.IPV6.BIN:/app/IP2LOCATION-LITE-ASN.IPV6.BIN
        - ip2location_data:/app/ip2location_data
  postgres:
    container_name: postgres
    image: postgres
    env_file:
        - .env
    restart: unless-stopped
    shm_size: 128mb

volumes:
    maxmind_data:
    ip2location_data:
