version: '3.7'
services:
  sybil-miner:
    container_name: sybil-miner
    image: sybil-miner:nightly
    ports:
        - "3001:3001"
    # You may also create a .env file in the same folder as the docker-compose.yml file
    environment:
        LOG_LEVEL: info
