services:
  miner:
    container_name: miner
    restart: unless-stopped
    image: taofuprotocol/tpn-subnet-miner:latest
    ports:
        - "3001:3001"
    # You may also create a .env file in the same folder as the docker-compose.yml file
    environment:
        LOG_LEVEL: info