services:

  # This postgres service is used for development only, you should NEVER use this file
  postgres:
    container_name: postgres
    image: postgres
    ports:
        - "5432:5432"
    env_file:
        - .env
    environment:
      - POSTGRES_PASSWORD
    restart: unless-stopped
    shm_size: 128mb
    healthcheck:  # Add healthcheck to confirm readiness
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5